"""Add is_general_recipient to User

Revision ID: b8e8f366754a
Revises: d6da2213039f
Create Date: 2024-12-07 19:52:40.280398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e8f366754a'
down_revision = 'd6da2213039f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_general_recipient', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_general_recipient')

    # ### end Alembic commands ###
